---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Keystone文件
    url: "/index.html"
  - title: 版本資訊
    entries:
    - title: Keystone STaaS 的新功能
      url: "/release-notes/whats-new.html"
    - title: 修正問題
      url: "/release-notes/fixed-issues.html"
    - title: 已知限制
      url: "/release-notes/known-limitations.html"
    - title: 已知問題
      url: "/release-notes/known-issues.html"
  - title: 歡迎使用Keystone
    url: "/concepts/overview.html"
  - title: 設定及設定Keystone
    entries:
    - title: 什麼是Keystone Collector
      url: "/installation/installation-overview.html"
    - title: 準備系統以安裝 Keystone Collector
      entries:
      - title: VMware vSphere需求
        url: "/installation/vapp-prereqs.html"
      - title: Linux 需求
        url: "/installation/linux-prereqs.html"
      - title: ONTAP 與 StorageGRID 需求
        url: "/installation/addl-req.html"
    - title: 安裝 Keystone Collector
      entries:
      - title: VMware vSphere部署
        url: "/installation/vapp-installation.html"
      - title: Linux安裝
        url: "/installation/linux-installation.html"
      - title: 自動完整性驗證
        url: "/installation/validation.html"
    - title: 設定Keystone Collector
      url: "/installation/configuration.html"
    - title: 監控系統健全狀況
      url: "/installation/monitor-health.html"
    - title: 升級 Keystone Collector
      url: "/installation/upgrade.html"
    - title: 設定 Keystone 的 AutoSupport
      url: "/installation/asup-config.html"
    - title: 收集以供計費的資料
      url: "/installation/data-collection.html"
  - title: Keystone服務可讓您做更多工作
    entries:
    - title: 檢視 Active IQ Digital Advisor 上的 Keystone 儀表板
      url: "/integrations/keystone-aiq.html"
    - title: 檢視使用詳細資料並產生報告
      url: "/integrations/aiq-keystone-details.html"
    - title: 管理 BlueXP 的 Keystone 訂閱
      url: "/integrations/keystone-cm.html"
  - title: 深入瞭解Keystone
    entries:
    - title: 支援的儲存容量
      url: "/concepts/supported-storage-capacity.html"
    - title: 指標與定義
      url: "/concepts/metrics.html"
    - title: Keystone中支援的儲存設備
      url: "/concepts/supported-storage-services.html"
    - title: Keystone中的服務層級
      url: "/concepts/service-levels.html"
    - title: 附加服務
      entries:
      - title: 資料分層
        url: "/concepts/data-tiering.html"
      - title: 進階資料保護
        url: "/concepts/adp.html"
      - title: 美國公民支援（USCS）
        url: "/concepts/uscs.html"
      - title: 不可回收、非揮發性元件及SnapLock 不符合要求
        url: "/concepts/nrnvc.html"
      - title: Keystone與Equinix
        url: "/concepts/equinix.html"
  - title: 深入瞭解服務層級
    entries:
    - title: 服務品質
      url: "/concepts/qos.html"
    - title: 服務層級的容量需求
      url: "/concepts/capacity-requirements.html"
    - title: 永續性 SLA
      url: "/concepts/sla-sustainability.html"
  - title: 帳單
    entries:
    - title: Keystone定價
      url: "/concepts/pricing.html"
    - title: 根據已提交的容量進行計費
      url: "/concepts/committed-capacity-billing.html"
    - title: 根據耗用容量進行計量
      url: "/concepts/consumed-capacity-billing.html"
    - title: 根據尖峰使用量進行計費
      url: "/concepts/burst-consumption-billing.html"
    - title: 根據雜項Volume類型進行收費
      url: "/concepts/misc-volume-billing.html"
    - title: 帳單排程
      url: "/concepts/billing-schedules.html"
  - title: 合作夥伴與客戶營運環境
    url: "/concepts/operational-models.html"
  - title: Keystone基礎架構
    entries:
    - title: 基礎架構詳細資料
      url: "/concepts/infra.html"
    - title: 元件
      url: "/concepts/components.html"
    - title: 資料流
      url: "/concepts/data-flow.html"
  - title: NetApp全球服務支援中心
    url: "/concepts/gssc.html"
  - title: 法律聲明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 開始使用
    links:
    - title: 什麼是 NetApp Keystone 功能？
      url: "/concepts/overview.html"
    - title: 在VMware vSphere上安裝Keystone Collector
      url: "/installation/vapp-installation.html"
    - title: 在Linux上安裝Keystone Collector
      url: "/installation/linux-installation.html"
    - title: 在 Digital Advisor 上檢視您的使用情形
      url: "/integrations/keystone-aiq.html"
    - title: 產生使用量報告
      url: "/integrations/aiq-keystone-details.html"
  - title: Keystone中支援的服務
    links:
    - title: Keystone服務層級
      url: "/concepts/service-levels.html"
    - title: 服務品質（QoS）
      url: "/concepts/qos.html"
    - title: 測量單位為何？
      url: "/concepts/metrics.html"
    - title: 支援的基礎儲存設備為何？
      url: "/concepts/supported-storage-services.html"
    - title: 我可以將支出從內部部署重新分配到雲端嗎？
      url: "/concepts/capacity-requirements.html#capacity-adjustments"
  - title: Keystone 定價與計費
    links:
    - title: 瞭解 Keystone 定價
      url: "/concepts/pricing.html"
    - title: 我的帳單排程
      url: "/concepts/billing-schedules.html"
    - title: 根據已提交的容量進行計費
      url: "/concepts/committed-capacity-billing.html"
    - title: 根據耗用容量進行計量
      url: "/concepts/consumed-capacity-billing.html"
    - title: 如果耗用的容量超過承諾容量、會發生什麼情況？
      url: "/concepts/burst-consumption-billing.html"
  - title: Keystone服務可讓您做更多工作
    links:
    - title: 瞭解您的支援團隊（Keystone GSSC）
      url: "/concepts/gssc.html"
    - title: 我可以如何處理冷資料或使用率較低的資料？
      url: "/concepts/data-tiering.html"
    - title: 如何保護我的 Keystone 資料？
      url: "/concepts/adp.html"
    - title: Keystone與BlueXP
      url: "/integrations/keystone-cm.html"
    - title: 美國公民支援
      url: "/concepts/uscs.html"
  - title: 瞭解更多資訊
    links:
    - title: Keystone 訂閱第 1 版（先前的 Keystone Flex 訂閱）
      url: https://docs.netapp.com/us-en/keystone/
    - title: Active IQ Digital Advisor
      url: https://docs.netapp.com/us-en/active-iq/index.html
    - title: 藍圖
      url: https://docs.netapp.com/us-en/cloud-manager-family/
    - title: Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/
