---
sidebar: sidebar 
permalink: concepts/components.html 
keywords: infrastructure component, deployment requirement, installation requirement 
summary: 瞭解在您的環境中啟用 NetApp Keystone STaaS 服務所需的元件。 
---
= Keystone服務所需的元件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要啟用NetApp Keystone STaaS 服務，您需要多個元件。在開始之前，請先查看這些組成部分。



== 站台需求

有些站台特定的需求、例如空間、機架、PDU、電力、 以及散熱、以及此處討論的其他網路和安全需求。



=== 空間

用於裝載Keystone基礎架構設備的場地空間（由客戶提供）。NetApp 會根據最終組態提供重量規格。



=== 機架

客戶營運產品中的四個柱式機架（由客戶提供）。在 NetApp 營運的產品中、 NetApp 或客戶可以視需求提供機架。NetApp 提供 42 個深機架。



=== PDU

您應提供電力分配單元（PDU）、連接至兩個獨立且受保護的電路、並具有足夠的C13插座。在客戶營運的產品中、在某些情況下、需要 C19 插座。在NetApp營運的產品中、NetApp或客戶可視需求提供PDU。



=== 強大威力

您應該提供所需的電力。NetApp 將根據 200V 額定值（典型 A 、 Max A 、典型 W 、最大 W 、電源線類型、 和數量）。所有元件都有備援電源供應器。NetApp 將提供機櫃內的電源線。



=== 散熱

NetApp 可根據最終組態和需求、提供散熱需求規格（一般 BTU 、最大 BTU ）。



=== 虛擬機器

基礎概念收集器和 ITOM 收集器的部署需要虛擬機器。有關安裝先決條件，請參閱link:../installation/installation-overview.html["Keystone Collector 安裝指南"]和link:../installation/itom-prereqs.html["ITOM Collector 的安裝需求"]。其他需求則在部署期間共用。



=== 部署選項

Keystone Collector 可透過下列方法部署：

* VMware OVA範本（需要VMware vCenter Server 6.7或更新版本）
* 客戶需提供一台運行下列作業系統之一的 Linux 伺服器：Debian 12、Red Hat Enterprise Linux 8.6 或更高版本的 8.x 版本、Red Hat Enterprise Linux 9.0 或更高版本，或 CentOS 7（僅限現有環境）。Keystone軟體使用以下方式安裝： `.deb` 或者 `.rpm` 軟體包取決於 Linux 發行版。


ITOM Collector 可透過下列方法進行部署：

* 客戶提供運行 Debian 12、Ubuntu 20.04 LTS、Red Hat Enterprise Linux (RHEL) 8.x、Red Hat Enterprise Linux 9.0、Amazon Linux 2023 或更高版本的 Linux 伺服器。
* 客戶提供執行 Windows Server 2016 或更新版本的 Windows 伺服器。
+

TIP: 建議使用的作業系統為 Debian 12 ， Windows Server 2016 或更新版本。





=== 網路

上傳軟體更新和使用資料時、需要對 _keystone NetApp ． com_ 進行輸出存取、這對於 Keystone Collector 和 AIOps 解決方案閘道的操作和維護非常重要。

根據客戶需求和使用的儲存控制器、NetApp可在客戶的站台提供10 GB、40 GB和100 GB的連線能力。

NetApp僅為NetApp提供的基礎架構裝置提供所需的收發器。您應該提供客戶裝置所需的收發器、以及連接至NetApp提供之Keystone基礎架構裝置的纜線。



== 遠端存取需求

客戶資料中心安裝的儲存基礎架構或客戶擁有的代管服務、以及Keystone作業中心之間、都需要網路連線。客戶負責提供運算與虛擬機器、以及網際網路服務。客戶還負責作業系統修補（非 OVA 型部署），並根據內部安全原則強化安全性。網路設計應採用安全的傳輸協定、而防火牆原則將由NetApp與客戶雙方核准。

NetApp需要存取安裝用於監控和管理的硬體和軟體元件、才能為Keystone客戶提供監控和計費等服務。最常見的方法是建立與客戶網路的虛擬私有網路（VPN）連線、並存取所需的資料。為了克服客戶從開啟防火牆連接埠到新服務所產生的任何作業複雜度、監控工具會啟動外部連線。NetApp 雲端應用程式，例如 ITOM 監控解決方案和期望，請使用此連線來執行各自的服務。此方法符合客戶的要求、即不開放防火牆連接埠、但可存取此服務的監控元件。
