---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Global Services Support Center, GSSC, Keystone support 
summary: NetApp全球服務支援中心GSSC 
---
= NetApp全球服務支援中心
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
利用NetApp全球服務與支援中心（GSSC）、《成功案例》（SESS- Success Manager）和《支援服務》（SESS- Service Delivery Manager）來執行支援服務。NetApp Keystone NetApp Keystone NetApp Keystone



== NetApp 全球服務與支援中心（ GSSC ）

NetApp 可遠端為 NetApp Keystone 客戶提供營運服務。這些服務涵蓋各種儲存管理活動的營運領域。這些服務包括資產與組態管理、容量與效能管理、變更管理、事件、事件與問題管理、服務要求履行及報告。NetApp會視需要展現控管狀態和支援證據。



== 其他資訊與支援聯絡人

NetApp全球服務與支援中心（GSSC）團隊主要支援NetApp Keystone 服務給客戶。您可以使用下列資訊聯絡支援團隊。

* 全球服務聯絡人：https://www.netapp.com/us/contact-us/support.aspx[]
* 如果您有需要提報的待處理個案/問題單、請傳送電子郵件至下列其中一個地址：keystone.services@netapp.com keystone.escalations@netapp.com
* NetApp使用OpsRamp,這是一種雲端型遠端閘道解決方案,可主動監控NetApp Keystone 及連線至該環境進行疑難排解。如需 OpsRamp 的相關資訊、請參閱 https://www.opsramp.com/#[]。



NOTE: 在合作夥伴營運模式中、租戶和租戶的服務要求會指派給合作夥伴的服務台。合作夥伴的支援工具可能已與 OpsRamp 和 GSSC 應用程式整合。只有 L3 問題會透過 GSSC 提報給 NetApp 。

如需詳細資訊、請參閱：

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* NetApp 產品文件https://docs.netapp.com["https://docs.netapp.com"^]




== GSSC監控

NetApp全球服務與支援中心（GSSC）可監控您產品和訂閱服務的健全狀況、提供遠端支援、並與Keystone Success Manager合作。所有監控相關Keystone訂購訂單相關產品的人員、均為美國公民土壤。

.Keystone成功管理程式
Keystone Success Manager是美國美國公民土壤。您NetApp Keystone 的《不確定協議》中有明確的責任。

如需相關資訊、請參閱 link:../concepts/uscs.html["美國公民支援（USCS）"]。
