---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v3, version 3 
summary: NetApp Keystone STaaS 服務使用數個詞彙來衡量指標。在使用 Keystone 服務第 3 版時，您可能希望了解有關這些術語的更多資訊。 
---
= Keystone 中使用的度量和定義
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 服務使用數個詞彙來衡量指標。在使用 Keystone 版本 3 (v3) 時，您可能想要了解更多有關這些術語的資訊。

Keystone STaaS 服務中會使用下列術語和定義來衡量指標：

* 容量測量單位：Gib、TiB和PIB
* IOPS：每秒處理的輸入/輸出運算元。
* 服務可用度
* 精確資料存取的持久性
* 延遲與速度




== 指標測量

* *容量測量單位為單位元組（GiB）、小單位元組（TiB）和小單位元組（PIB）*：使用基礎為1024的資料儲存容量測量（1 GiB = 101010^3^位元組、1 TiB = 104^位元組、1 PiB = 1010%5^位元組）。
* *IOPS 中的操作計數器圖表*：應用程式請求的每秒協定操作數。
* *可用度*：以服務已成功回應的I/O要求數百分比（除以對服務提出的I/O要求總數）計算。這是在一個月內的服務劃分時進行測量、不包括排定的服務停機時間、或客戶所提供設施、網路或其他服務的不可用性。
* *持久性*：存取資料時不損失保真度的百分比、不包括客戶造成的刪除或毀損。
* *延遲*：服務從用戶端接收到I/O要求的時間、以服務標界（儲存控制器I/O連接埠）為測量單位。




=== 效能指標

以下效能指標適用於統一和區塊最佳化服務：

*統一服務：*

* *IOPS*：對於具有 NFS 的 ONTAP 9.16.1，每個效能等級實例支援隨機訪問，讀取率為 70%，寫入率為 30%，區塊大小為 8 KB，延遲為 1 毫秒（標準為 4 毫秒）。
* *吞吐量*：對於具有 NFS 的 ONTAP 9.16.1，每個效能等級實例都支援 100% 讀取和 32 KB 區塊大小的順序存取。


*阻止最佳化服務：*

* *IOPS*：對於具有 FCP 的 ONTAP 9.16.1，每個效能等級實例支援讀取率為 70%、寫入率為 30%、區塊大小為 8 KB 且延遲為 1 毫秒的隨機存取。
* *吞吐量*：對於具有 FCP 的 ONTAP 9.16.1，每個效能等級實例都支援 100% 讀取和 64 KB 區塊大小的順序存取。

