---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability 
summary: Keystone服務的度量計算與定義 
---
= Keystone服務中使用的度量和定義
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
下列詞彙與定義用於NetApp Keystone 《不完整（基礎概念）》（Keystone）STaaS服務、以測量數據：

* 容量測量單位：Gib、TiB和PIB
* IO密度：IOPS/TiB：每秒處理的輸入/輸出作業數、以工作負載所耗用的總空間為單位（以TB為單位）。
* 服務可用度
* 精確資料存取的持久性
* 延遲與速度




== 指標測量

* *容量測量單位為單位元組（GiB）、小單位元組（TiB）和小單位元組（PIB）*：使用基礎為1024的資料儲存容量測量（1 GiB = 101010^3^位元組、1 TiB = 104^位元組、1 PiB = 1010%5^位元組）。
* *作業計數器表（以IOPS/TiB*為單位）：應用程式要求的每秒傳輸協定作業量、除以工作負載使用的磁碟區大小。
* *可用度*：以服務已成功回應的I/O要求數百分比（除以對服務提出的I/O要求總數）計算。這是在一個月內的服務劃分時進行測量、不包括排定的服務停機時間、或客戶所提供設施、網路或其他服務的不可用性。
* *持久性*：存取資料時不損失保真度的百分比、不包括客戶造成的刪除或毀損。
* *延遲*：服務從用戶端接收到I/O要求的時間、以服務標界（儲存控制器I/O連接埠）為測量單位。




=== 處理量效能指標

處理量效能指標僅適用於檔案和區塊服務、其基礎為：

* 32 KB區塊大小
* 70%讀取/ 30%寫入I/O混合




=== IO密度差異

以IOPS/TiB和/或Mbps/TiB為單位計算的IO密度會因下列因素而異：

* 工作負載特性
* 延遲、不包括下列項目：
+
** 應用程式延遲
** 主機延遲
** 在控制器連接埠之間傳輸資料時、客戶網路的延遲
** 資料傳輸至物件存放區的例行延遲、以FabricPool 供選擇
** QoS會自動套用延遲、使IO保持在服務層級上限內


* 使用者與Snapshot複本資料、被視為已使用容量的一部分
* 無論ONTAP 磁碟區中的資料量為何、每個資料區上所配置的絕對最小IOPS：
+
** 極致：1、000 IOPS
** Premium：500 IOPS
** 效能、標準和價值：75 IOPS


* 使用進階資料保護附加服務時、目標延遲僅適用於處理來自本機儲存設備的IO要求。




=== Volume AQO

每ONTAP 個供應區都應套用適用的調適性服務品質（AQO）原則。否則、每個未套用AQO原則的磁碟區內容量、將以最高服務層級的費率計費。
