---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: 瞭解特定組態的 Keystone 帳單、包括複製的磁碟區、進階資料保護等。 
---
= Keystone計費的其他案例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
了解版本 3 (v3) 中特定配置的Keystone計費可以協助您最佳化服務使用量並管理成本。配置包括複製磁碟區、臨時磁碟區、 SnapMirror目標、LUN 和系統/根磁碟區。



== 複製磁碟區的收費

如果將磁碟區複製到 ONTAP 支援區中、並將其用於備份及還原資料、您可以繼續使用複本、而無需支付任何額外費用。然而、貴企業長期用於任何其他用途的複製磁碟區則需支付費用。

請注意下列事項：

* 只要實體磁碟區的大小低於父磁碟區的 10% 、就不需要充電（與父磁碟區中使用的實體容量相比、複製磁碟區中使用的實體容量）。
* 克隆卷沒有 24 小時的寬限期。僅考慮克隆卷的大小。
* 一旦複製磁碟區超過父磁碟區實體大小的 10% 、複製就會以標準磁碟區（邏輯使用容量）計費。




== 暫用磁碟區收費

有時 ONTAP 、當搬移 Volume 時、會由現象開發出暫用（ TMP ） Volume 。這些暫存磁碟區的壽命很短、而且不會測量這些磁碟區的使用量以供計費。



== SnapMirror 目的地收費

SnapMirror 目標磁碟區的定價（無論用於災難復原或長期保留）均基於分配給目標磁碟區的效能服務等級。資料保護無需額外付費。



== LUN 計費

對於 LUN，計費基於磁碟區的效能服務等級。



== 系統和根磁碟區

系統和根磁碟區會在Keystone服務的整體監控中受到監控、但不會計入或計費。這些磁碟區的使用量可免除計費。



== SnapMirror 目的地收費

SnapMirror 目的地 Volume 的價格是由來源上所指派服務層級的調適性 QoS 原則所規範。不過、如果來源沒有相關的調適性 QoS 原則、則目的地會根據最低的可用服務層級收費。



== LUN 計費

對於 LUN 、遵循的計費模式與受調適性 QoS 原則管理的磁碟區相同。如果在 LUN 上設定個別的調適性 QoS 原則、則：

* LUN 的大小會根據該 LUN 的相關服務層級來計算、以供使用。
* 磁碟區中剩餘的空間（如果有）是根據磁碟區上所設定服務層級的自適應 QoS 原則來收費的。




== 系統和根磁碟區

系統和根磁碟區會在Keystone服務的整體監控中受到監控、但不會計入或計費。這些磁碟區的使用量可免除計費。
