---
sidebar: sidebar 
permalink: concepts/misc-volume-billing-v2.html 
keywords: Billing and miscellaneous scenarios 
summary: 瞭解特定組態的 Keystone 帳單、包括複製的磁碟區、進階資料保護等。 
---
= Keystone計費的其他案例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
了解 Keystone 版本 2 (v2) 中特定配置的計費方式，可以協助您最佳化服務使用情況並管理成本。這些配置包括複製磁碟區、進階資料保護、臨時磁碟區、QoS 策略、SnapMirror 目標、LUN 以及系統/根磁碟區。



== 複製磁碟區的收費

如果將磁碟區複製到 ONTAP 支援區中、並將其用於備份及還原資料、您可以繼續使用複本、而無需支付任何額外費用。然而、貴企業長期用於任何其他用途的複製磁碟區則需支付費用。

請注意下列事項：

* 只要實體磁碟區的大小低於父磁碟區的 10% 、就不需要充電（與父磁碟區中使用的實體容量相比、複製磁碟區中使用的實體容量）。
* 克隆卷沒有 24 小時的寬限期。僅考慮克隆卷的大小。
* 一旦複製磁碟區超過父磁碟區實體大小的 10% 、複製就會以標準磁碟區（邏輯使用容量）計費。




== 進階資料保護計費

進階資料保護使用 NetApp MetroCluster 在兩個實體分隔的叢集之間鏡射資料。對於鏡射式集合體、資料會在每個叢集上寫入兩次。MetroClusterKeystone服務會獨立收取每一端的使用費用、因此會產生兩個相同的使用記錄。附加費用會套用至訂閱中的所有容量、無論資料是位於來源、或是鏡射或無鏡射的資料。

如果您透過ONTAP 《系統管理程式》（System Manager）或Active IQ Unified Manager 《統一化管理程式》（Unified Manager）監控叢集、您可能會發現這些工具和Keystone上報告的使用量差異。System Manager和Unified Manager不會在鏡射（遠端）叢集上報告磁碟區、因此會報告Keystone服務報告的使用量數據一半。

.範例：
站台A和站台B是MetroCluster 以不一樣的組態設定。當使用者在站台 A 中建立 10TB 的磁碟區時、站台 B 會建立相同的 10TB 磁碟區Keystone可識別每個站台的10TB使用量、總計增加20TB。System Manager 和 Unified Manager 會回報站台 A 建立的 10TB Volume 、但不會回報站台 B 中的 10TB Volume

此外、在具有進階資料保護功能的 Keystone 系統上建立的所有磁碟區、都會計入進階資料保護的使用量、無論這些磁碟區是否已鏡射。



== 暫用磁碟區收費

有時 ONTAP 、當搬移 Volume 時、會由現象開發出暫用（ TMP ） Volume 。這些暫存磁碟區的壽命很短、而且不會測量這些磁碟區的使用量以供計費。



== 計費和調適性 QoS 原則

Keystone 會根據服務層級來測量使用量。每個服務層級都與特定的調適性服務品質（QoS）原則相關聯。在部署期間、系統會通知您所訂閱 Keystone 服務的每個調適性 QoS 原則詳細資料。在儲存管理作業期間、請確保您的磁碟區已根據您訂閱的服務層級指派適當的調適性 QoS 原則、以避免意外的計費。如需 ONTAP 中調適性 QoS 原則的詳細資訊，請參閱link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["透過 QoS 總覽來保證處理量"^]。



== SnapMirror 目的地收費

SnapMirror 目的地 Volume 的價格是由來源上所指派服務層級的調適性 QoS 原則所規範。不過、如果來源沒有相關的調適性 QoS 原則、則目的地會根據最低的可用服務層級收費。



== LUN 計費

對於 LUN 、遵循的計費模式與受調適性 QoS 原則管理的磁碟區相同。如果在 LUN 上設定個別的調適性 QoS 原則、則：

* LUN 的大小會根據該 LUN 的相關服務層級來計算、以供使用。
* 磁碟區中剩餘的空間（如果有）是根據磁碟區上所設定服務層級的自適應 QoS 原則來收費的。




== 系統和根磁碟區

系統和根磁碟區會在Keystone服務的整體監控中受到監控、但不會計入或計費。這些磁碟區的使用量可免除計費。
