---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone 提供隨成長付費模式、滿足您靈活且可擴充的消費需求。 
---
= 了解Keystone定價
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone STaaS 按使用量付費訂閱服務提供靈活且可擴展的消費，並為您的儲存需求提供可預測的預付定價。

Keystone為您提供以下計費功能：

* 您可以根據 IOPS 和延遲承諾容量付費，以滿足各種工作負載需求。不同的效能服務層級 - Extreme、Premium、Standard、Value、Object 和Cloud Volumes ONTAP可讓您根據購買的效能服務等級管理儲存。
* 它提供可預測的計費方式、可針對已提交的容量、以及針對可變（突發）容量使用量的「依使用量付費」。
* 您可以針對硬體、核心作業系統及支援選擇套裝組合價格、只需支付一美元 / TiB 的價格。對於每種儲存類型、統一儲存、區塊儲存、最佳化儲存、物件儲存或雲端儲存服務，您都有一張發票。
* 您可以選擇彈性的服務期限和付款方式，例如按月、按季度、按半年或按年。


Keystone計費是根據已提交的容量和可變的突發消耗量來計算。

如需Keystone支援的不同容量資訊、請參閱 link:../concepts/supported-storage-capacity.html["Keystone中支援的儲存容量"]。

*相關資訊*

* link:../concepts/committed-capacity-billing.html["根據已提交的容量進行計費"]
* link:../concepts/consumed-capacity-billing.html["根據耗用容量進行計量"]
* link:../concepts/burst-consumption-billing.html["根據尖峰使用量進行計費"]
* link:../concepts/misc-volume-billing.html["根據雜項Volume類型進行收費"]
* link:../concepts/billing-schedules.html["帳單排程"]

