---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Keystone中的服務品質 
---
= Keystone中的服務品質（QoS）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
儲存服務品質（QoS）是一項關鍵技術、可確保應用程式獲得一致且可預測的效能。如果沒有QoS、某些工作負載（例如多個系統開機）可能會佔用一段時間的整個資源、並影響其他工作負載。如需QoS的相關資訊、請參閱 https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["透過 QoS 總覽來保證處理量"^]。

應用QoS可確保應用程式每次都能獲得一致的效能。NetApp ONTAP 旨在定義QoS的兩個參數： https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-throughput-ceilings-qos-max["QoS最大值"^]和處理量最低 https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-throughput-floors-qos-min["QoS最低"^]。QoS最大值代表工作負載可達到的IOPS、Mbps或IOPS和Mbps的最大數目。另一方面、 QoS Min 則保證工作負載的處理量不會低於特定的 IOPS 或 Mbps 、或 IOPS 和 Mbps 。



== 調適性QoS

隨QoS原則的大小變化、會自動套用調適性QoS（AQO）作為Keystone服務、以維持IOPS與TB/GBs的比率。如需AQO原則的相關資訊、請參閱 https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["關於調適性QoS"^]。

Keystone提供AQO原則、讓您在叢集正式作業後即可設定。您應確保所有磁碟區都與系統中已建立且可用的正確AQO原則相關聯。


NOTE: 如果您尚未在磁碟區上正確套用AQO原則、則這些磁碟區將會依照您的訂閱、以最高服務層級進行測量和收費。這可能導致意外的突發費用。



== 自適性QoS原則群組的組態

您可以設定調適性QoS（AQO）原則、自動將處理量上限或樓層調整為Volume大小。若要設定原則、您應注意下列事項：

* *原則群組名稱*：AQO原則群組的名稱。例如、 `Keystone_extreme`。
* * vserver*：Vserver或儲存VM（儲存虛擬機器）的名稱。
* *預期IOPS *：ONTAP 只要有效能保證、即可提供最低IOPS / TiB數量。
* *尖峰IOPS *：在效能受到限制之前、磁碟區可用的最大IOPS / TiB數量。
* *預期IOPS分配*：此欄位可控制磁碟區的預期IOPS是否取決於已分配或已使用的磁碟區大小。在Keystone中、這是根據已分配的空間而定。
* *尖峰IOPS配置*：此欄位可控制磁碟區可用的尖峰IOPS是否取決於已分配或已使用的磁碟區大小。在Keystone中、這是根據已用空間而定。
* *絕對最小IOPS *：如果磁碟區大小非常小、將套用至磁碟區的預期IOPS最低數目、否則會導致不可接受的IOPS數目。此值預設為1、000 `Extreme`、500代表 `Premium`和250（用於） `Performance`、75表示 `Standard` 和 `Value` 服務層級：
+

NOTE: 這不是IOPS密度（例如75 IOPS/TiB）、而是絕對最小IOPS數。



如需IO密度的相關資訊、請參閱 link:../concepts/metrics.html["Keystone服務中使用的度量和定義"]。如需AQO原則群組的詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["使用調適性QoS原則群組"^]。



== 調適性QoS原則的設定

下列各節將說明各服務層級的調適性QoS（AQO）原則設定。此處提供的每個服務層級的最小和最大Volume大小、可為磁碟區提供最佳的IOPs和延遲值。在這些準則之外建立太多磁碟區、可能會對這些磁碟區的效能造成負面影響。



=== 至尊服務層級的設定

Extreme服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* 最小Volume大小：100GiB、0.1TiB
* 最大Volume大小：10TiB




=== 優質服務層級的設定

優質服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* 最小Volume大小：500GiB、0.5TiB
* 最大Volume大小：50TiB




=== 效能服務層級的設定

效能服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* 最小Volume大小：500GiB、0.5TiB
* 最大Volume大小：80TiB




=== 標準服務層級的設定

標準服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小Volume大小：1TiB
* 最大Volume大小：100TiB




=== 價值服務層級的設定

價值服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小Volume大小：1TiB
* 最大Volume大小：100TiB




== 區塊大小計算

請在使用下列設定來計算區塊大小之前、先注意以下幾點：

* IOPS/TiB = Mbps/TiB除以（區塊大小* 1024）
* 區塊大小以KB / IO為單位
* TIB = 1024GiB；GiB = 1024MiB；MIB= 1024KiB；KiB = 1024Bytes；根據基礎2
* TB = 1000GB；GB = 1000MB；MB = 1000KB；KB = 1000Bytes；根據基礎10


.區塊大小計算範例
若要計算A服務層級的處理量、例如「Extreme」服務層級：

* IOPS上限：12、288
* 每I/O區塊大小：32KB
* 最大處理量=（12288 * 32 * 1024）/（101010* 1024）= 384MBps / TiB


如果某個磁碟區有700GiB的邏輯已用資料、可用的處理量將是：

「最大處理量= 384 * 0.7 = 268.8MBps」
