---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Keystone中的服務品質 
---
= Keystone中的服務品質（QoS）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
儲存服務品質（QoS）是一項關鍵技術、可確保應用程式獲得一致且可預測的效能。如果沒有 QoS 、某些工作負載（例如用於開機多個系統的工作負載）可能會在一段時間內消耗大部分或全部資源、並影響其他工作負載。如需QoS的相關資訊、請參閱 https://["透過 QoS 總覽來保證處理量"^]。



== 調適性QoS

Keystone 服務會使用 Adaptive QoS （ AQO ）、根據磁碟區大小來動態維持 IOPS/TiB 比率。如需AQO原則的相關資訊、請參閱 https://["關於調適性QoS"^]。

Keystone提供AQO原則、讓您在叢集正式作業後即可設定。您應確保所有磁碟區都與系統中已建立且可用的正確AQO原則相關聯。

如果 ONTAP Volume 未套用 AQO 原則、則該磁碟區不符合法規要求。沒有 QoS 原則的磁碟區是系統提供任何可用輸入輸出作業的最後一個優先順序清單。不過、如果有任何輸入輸出作業可用、則該磁碟區可能會使用所有可用的 IOS 。


NOTE: 如果您尚未將 AQO 原則套用至磁碟區、則會根據您的訂閱、以最高的服務層級來測量這些磁碟區並收取費用。這可能導致意外的突發費用。



== 調適性 QoS 設定

Adaptive QoS （ AQO ）設定會因服務層級而異。

|===


| * 政策名稱 * | * 極致 * | * 優質 * | *效能* | * 標準 * | * 價值 * 


| * 預期的 IOPS * | 6 、 144 | 2 、 048 | 1 、 024 | 256 | 64 


| * 預期的 IOPS 分配 * 5+| 已分配空間 


| * 尖峰 IOPS * | 12288/3 | 4 、 096 | 2 、 048 | 512 | 128/128 


| * 尖峰 IOPS 配置 * 5+| 已用空間 


| *區塊大小* 5+| 32 萬 
|===


== 自適性QoS原則群組的組態

您可以設定調適性QoS（AQO）原則、自動將處理量上限或樓層調整為Volume大小。並非所有 Keystone 服務層級都符合預設的 ONTAP QoS 原則。您可以為他們建立自訂 QoS 原則。若要設定原則、您應注意下列事項：

* *原則群組名稱*：AQO原則群組的名稱。例如、 `Keystone_extreme`。
* * vserver*：Vserver或儲存VM（儲存虛擬機器）的名稱。
* * 預期的 IOPS * ：每個磁碟區的每個分配 TiB 的 IOPS 下限、系統會在有足夠的系統 IOPS 可用時嘗試提供。
* * 尖峰 IOPS * ：每個磁碟區的每個已使用 TiB IOPS 最大數目、系統允許磁碟區在透過注入延遲來節流 IOPS 之前達到。
* * 預期的 IOPS 分配 * ：此參數可控制磁碟區的預期可用 IOPS 、是否取決於磁碟區的分配或使用大小。在Keystone中、這是根據已分配的空間而定。
* * 尖峰 IOPS 分配 * ：此參數可控制磁碟區可用的尖峰 IOPS 、是否根據已分配或已使用的磁碟區大小而定。在Keystone中、這是根據已用空間而定。
* *絕對最小IOPS *：如果磁碟區大小非常小、將套用至磁碟區的預期IOPS最低數目、否則會導致不可接受的IOPS數目。此值預設為1、000 `Extreme`、500代表 `Premium`和250（用於） `Performance`、75表示 `Standard` 和 `Value` 服務層級：
+

NOTE: 這不是IOPS密度（例如75 IOPS/TiB）、而是絕對最小IOPS數。



如需IO密度的相關資訊、請參閱 link:../concepts/metrics.html["Keystone服務中使用的度量和定義"]。如需AQO原則群組的詳細資訊、請參閱 https://["使用調適性QoS原則群組"^]。



== 調適性QoS原則的設定

下列各節將說明各服務層級的調適性QoS（AQO）原則設定。此處提供的每個服務層級的最小和最大Volume大小、可為磁碟區提供最佳的IOPs和延遲值。在這些準則之外建立太多磁碟區、可能會對這些磁碟區的效能造成負面影響。



=== 至尊服務層級的設定

Extreme服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* 最小Volume大小：100GiB、0.1TiB
* 最大Volume大小：10TiB




=== 優質服務層級的設定

優質服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* 最小Volume大小：500GiB、0.5TiB
* 最大Volume大小：50TiB




=== 效能服務層級的設定

效能服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* 最小Volume大小：500GiB、0.5TiB
* 最大Volume大小：80TiB




=== 標準服務層級的設定

標準服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小Volume大小：1TiB
* 最大Volume大小：100TiB




=== 價值服務層級的設定

價值服務層級的設定與命令：

* 命令範例：


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* 最小Volume大小：1TiB
* 最大Volume大小：100TiB




== 區塊大小計算

請在使用下列設定來計算區塊大小之前、先注意以下幾點：

* IOPS/TiB = Mbps/TiB除以（區塊大小* 1024）
* 區塊大小以KB / IO為單位
* TIB = 1024GiB；GiB = 1024MiB；MIB= 1024KiB；KiB = 1024Bytes；根據基礎2
* TB = 1000GB；GB = 1000MB；MB = 1000KB；KB = 1000Bytes；根據基礎10


.區塊大小計算範例
若要計算A服務層級的處理量、例如「Extreme」服務層級：

* IOPS上限：12、288
* 每I/O區塊大小：32KB
* 最大處理量=（12288 * 32 * 1024）/（101010* 1024）= 384MBps / TiB


如果某個磁碟區有700GiB的邏輯已用資料、可用的處理量將是：

「最大處理量= 384 * 0.7 = 268.8MBps」
