---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: 了解 NetApp Keystone STaaS 服務版本 3 支援的儲存容量類型。 
---
= Keystone 中的儲存容量類型
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS 使用多種容量術語來衡量、承諾和計費儲存資源。了解這些術語將有助於您規劃訂閱，並解讀您的使用報告和帳單。



== 邏輯容量

這是在應用儲存陣列提供的任何資料效率之前儲存使用者資料所需的儲存容量。



== 承諾容量

訂購期間每月計費的最低邏輯容量：

* 容量會分配給每個效能服務層級執行個體，以供統一或區塊最佳化儲存設備使用，或分配給每個 AFF 叢集。
* 承諾容量和額外的效能服務等級可以在期限內添加。




=== 已認可容量的變更

訂閱期間、您可以根據特定條件變更已承諾的容量。如需容量增加和減少規則的完整詳細資料、請參閱link:../concepts/capacity-requirements.html["Keystone效能服務等級的容量要求"]。若要申請變更、請聯絡您的 Keystone Success Manager (KSM) 或link:../concepts/support-services.html["NetApp 支援"]。



== 已用容量

已使用容量是指服務目前正在使用的容量（以 TiB 儲存為單位）。根據資料儲存類型的不同，其計算方式也不同：

* *統一或區塊最佳化儲存*：消耗的容量是根據訂購過程中選擇的容量類型（邏輯或實體）計算的。計算是按效能服務等級實例執行的。
+
.. *邏輯容量*：它是以下內容的總和：
+
*** 在儲存陣列資料效率之前計量邏輯容量，用於儲存所有實例和類型的客戶數據，例如副本、鏡像副本、版本和克隆。
*** 用於儲存快照和某些克隆的元資料和差異資料的實體容量。
*** 任何厚配置的物理容量。


.. *身體能力*：它是以下各項的總和：
+
*** 計量實體容量、儲存陣列資料效率之後、用於儲存所有執行個體和類型的客戶資料、例如複本、鏡射複本、版本和複本。
*** 用於儲存快照元資料和差異資料的實體容量。
*** 任何厚配置的物理容量。




* *AFF 儲存設備*：以 AFF 叢集為單位計算，計算方法為以下項目的總和：
+
** 計量實體容量、儲存陣列資料效率之後、用於儲存所有執行個體和類型的客戶資料、例如複本、鏡射複本、版本和複本。
** 用於儲存快照元資料和差異資料的實體容量。
** 任何厚配置的物理容量。


* *物件儲存*：已消耗容量是指用於儲存所有節點上所有執行個體和客戶資料類型的計量實體容量。此計算基於已配置的資訊生命週期管理 (ILM) 策略。
* *Cloud Volumes ONTAP*：已消耗容量以所有 Cloud Volumes ONTAP 磁碟區的計量配置邏輯容量計算。




== 突發容量

NetApp Keystone STaaS 服務可讓您在承諾容量的基礎上使用額外容量，以實現效能服務等級。這稱為突發容量使用。

請注意以下幾點：

* Keystone 訂單中會約定突發容量限制。通常預設為每個效能服務等級執行個體或每個 AFF 叢集承諾容量的 20% ，對於統一化儲存設備和區塊最佳化儲存設備，也可以選擇將突發容量限制設為承諾容量的 40% 或 60% 。
* 突發容量消耗以與所選資料儲存類型（DST）和效能服務等級對應的承諾容量相同的費率計費。
* Keystone STaaS 服務自開始日期起提供 60 天的突發豁免期。




== 計費容量

每月帳單 = （提交容量 [TiB] * 提交率 [$/TiB] ） + （每日平均資源配置突發容量 [TiB] * 資源暴增率 [$/TiB] ）。每月帳單包含根據承諾容量所計算的最低費用。

每月帳單金額會根據每日平均突發容量使用量而異、超過最低收費。
