---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: 如果您需要協助，請聯絡 NetApp Keystone 支援團隊。 
---
= 取得 Keystone 的說明
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Keystone 支援團隊和 Keystone 成功經理（ KSM ）負責為 Keystone 訂閱提供服務。如果您需要協助，可以聯絡 Keystone 支援團隊。



== NetApp Keystone 支援

NetApp 可遠端為 NetApp Keystone 客戶提供營運服務。這些服務涵蓋各種儲存管理活動的營運領域。這些服務包括資產與組態管理、容量與效能管理、變更管理、事件、事件與問題管理、服務要求履行及報告。NetApp 會視需要示範控管狀態和佐證證。



== 其他資訊

NetApp 使用 ITOM 監控解決方案主動監控並連線至 NetApp Keystone 環境進行疑難排解。


NOTE: 在合作夥伴營運模式中、租戶和租戶的服務要求會指派給合作夥伴的服務台。合作夥伴的支援工具可能與 ITOM 解決方案整合。

如需Keystone服務的詳細資訊、請參閱：

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* NetApp 產品文件https://docs.netapp.com["https://docs.netapp.com"^]




== Keystone 支援監控

NetApp Keystone 支援可監控您產品和訂閱服務的健全狀況，提供遠端支援，並與 Keystone 成功經理合作。

.Keystone成功管理程式
Keystone Success Manager （ KSM ）會與您密切合作、提供 Keystone 服務、並在每週或每月帳單和營運報告上更新您的資訊。職責請詳列NetApp Keystone 於您的《個人資訊協議》中。



== 正在產生服務要求

在就職期間、如果您獲得存取和使用NetApp Keystone 此功能的認證資料、您可以使用入口網站針對與Keystone訂閱相關的問題產生服務要求：

https://netappkeystone.service-now.com/csm[]

在提出服務要求之前、請先確定系統詳細資料、記錄及相關資訊已備妥。當您提出服務要求時， Keystone 支援團隊會收到支援服務單，並存取疑難排解資訊。您可以依照 ServiceNow 通知單瞭解狀態和解決方案。

如需新增支援服務組合的相關資訊、請參閱 link:../installation/monitor-health.html["產生並收集支援套裝組合"]。

如果您有需要提報的待處理個案/問題單、請傳送電子郵件至下列其中一個地址：keystone.services@netapp.com keystone.escalations@netapp.com
