---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Keystone STaaS 服務支援 ONTAP 和 StorageGRID 。 
---
= Keystone中支援的儲存設備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS 服務版本 3 (v3) 支援 NetApp 和 Cloud Volumes ONTAP 的統一、區塊最佳化和物件儲存。

每種儲存類型包括：

* *統一儲存*：包括檔案、區塊和 S3 物件存儲，可在 NetApp ONTAP AFF 和 FAS 系統上使用。
* *區塊最佳化儲存*：包括 NetApp ONTAP ASA 系統上可用的區塊儲存。
* *物件儲存*：包括 NetApp StorageGRID 系統上可用的物件儲存。


Keystone STaaS可為您的儲存設備提供標準和選用的服務。

* Keystone STaaS標準服務*：標準服務包含在基本訂閱中、不需另外付費。

* Keystone STaaS附加服務*：這些是可選的收費服務、除了提供標準Keystone STaaS訂閱服務之外、還能提供額外的公用程式與效益。

Keystone STaaS 服務可以同時使用。例如，雲端儲存訂閱的期限可以與統一儲存、區塊最佳化儲存和物件儲存訂閱的期限相同。雲端服務可在現有儲存訂閱的服務期間內隨時納入。但是，如果您不打算續訂現有的統一儲存、區塊最佳化儲存或物件儲存訂閱，則在訂閱的最後 90 天內無法新增雲端儲存訂閱。



== 統一、區塊最佳化和物件儲存服務

Keystone STaaS 服務適用於統一儲存、區塊最佳化儲存和物件存儲，支援多種功能和協議，如下表所述：

|===
| 儲存設備 | 平台 | 通訊協定 | 支援的功能 


 a| 
統一化儲存設備
 a| 
ONTAP
 a| 
NFS與CIFS
 a| 
支援所有 ONTAP One 功能



 a| 
區塊最佳化儲存
 a| 
ONTAP
 a| 
FC與iSCSI
 a| 
支援所有 ONTAP One 功能



 a| 
物件儲存
 a| 
StorageGRID
 a| 
S3
 a| 
支援所有 ONTAP One 功能

|===
要了解有關 ONTAP One 的更多信息，請參閱link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP 授權總覽"^]和link:https://www.netapp.com/blog/ontap-one/["ONTAP One：集 ONTAP 全部功能於一身"^] 。



== 雲端儲存服務

Keystone STaaS提供雲端儲存服務。Keystone STaaS可在Cloud Volumes ONTAP Amazon Web Services（AWS）、Microsoft Azure和Google Cloud Platform上支援「資料不全」管理功能。


NOTE: NetApp並未提供由NetApp所需的超純量運算、儲存及網路服務Cloud Volumes ONTAP 、作為Keystone STaaS訂閱的一部分；這些訂閱必須直接向超純量雲端服務供應商購買。
