---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: 附加元件、額外服務詳細資料、資料分層 
---
= 資料分層
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
根據預設、Keystone基礎服務包含分層功能、可與訂閱的檔案和區塊服務一起識別使用較少的資料、並將其分層至由NetApp擁有、部署及管理的冷儲存設備。如果您想要將冷資料分層至任何非NetApp儲存設備（例如任何企業雲端儲存設備）、您可以使用附加服務進行分層。

只有當資料分層至任何非NetApp儲存設備（例如Amazon Web Services（AWS）S3、Azure Blob、Google Cloud Platform（GCP）及其他支援的S3相容協力廠商物件儲存設備）時、才需要分層附加服務。

如需基礎儲存設備和雲端儲存服務的相關資訊、請參閱 link:../concepts/supported-storage-services.html["支援的儲存服務"]。

如需服務層級的相關資訊、請參閱 link:../concepts/service-levels.html["Keystone中的服務層級"]。

分層功能運用 NetApp FabricPool 的技術、可將資料自動分層至內部或外部的低成本物件儲存層。有了這項功能、不常存取的資料會根據議定的服務、自動分層至內部部署或雲端的低成本儲存設備。

附加分層服務可讓您從極致、優質、效能、標準及價值層級分層至物件目標。熱層和冷層分別計費和開立發票。

資料分層可隨時新增、價格不變、而且在冷熱比方面增加更多靈活度。要階層化的熱/冷資料比例並未固定、且分層實體區塊的數量會分開測量。

如需詳細資訊、請參閱下列計算：

如果冷儲存層的目標是：

* 價值層（最高500 TiB）、物件層（>500 TiB）、現有SGWS網格（客戶擁有）–不需額外付費；這是基本儲存服務的一部分。
* 公有雲（AWS、Azure、Google）和任何其他第三方支援的物件儲存設備、會額外收取資料容量費用、以分層收費的形式進行。


附加分層訂閱所涉及的費用並非一次性收費。您必須支付整個期限的費用、才能維持Keystone內部部署檔案與區塊服務與協力廠商支援的物件儲存目標之間的分層關係。

這項服務只能將冷資料分層至較便宜的目標儲存設備、而非公有雲/超純量基礎架構成本。


NOTE: 超純量型運算與儲存基礎架構並非由NetApp提供、因此您必須向超純量雲端服務供應商購買。
