---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: 附加元件、額外服務詳細資料、資料分層 
---
= 資料分層
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
支援NetApp所擁有、部署及管理的冷儲存設備、可識別使用頻率較低的資料、並利用訂閱的檔案和區塊服務來分層處理。NetApp Keystone

您可以訂閱此附加服務、作為Keystone訂閱的一部分。如需基礎儲存設備和雲端儲存服務的相關資訊、請參閱 link:../concepts/supported-storage-services.html["支援的儲存服務"]

如需服務層級的相關資訊、請參閱 link:../concepts/service-levels.html["Keystone中的服務層級"]


NOTE: 資料分層至NetApp儲存目標預設包含在檔案與區塊儲存服務層中。只有在資料分層任何非NetApp儲存設備（例如AWS S3、Azure Blob和EMC ECS）時、才需要附加服務。

分層功能運用 NetApp FabricPool 的技術、可將資料自動分層至內部或外部的低成本物件儲存層。有了這項功能、不常存取的資料會根據議定的服務、自動分層至內部部署或雲端的低成本儲存設備。

分層服務可讓您從極致、優質、效能、標準及價值層級分層至物件目標。熱層和冷層分別計費和開立發票。您可以隨時新增資料分層、無需變更定價、並在熱/冷比率方面增加更多靈活度。

請進行下列計算、以便更深入瞭解：

如果冷儲存層的目標是：

* 價值層（最高500 TiB）、物件層（>500 TiB）、現有SGWS網格（客戶擁有）–不需額外付費、而且是基本儲存服務的一部分。
* 公有雲（AWS、Azure、Google）和任何其他第三方支援的物件儲存設備、會額外收取資料容量費用、以分層收費的形式進行。


附加分層訂閱所涉及的費用並非一次性費用、您必須支付整個期間的費用、才能維持Keystone內部部署檔案與區塊服務與協力廠商支援的物件儲存目標之間的分層關係。

這項服務只能將冷資料分層至較便宜的目標儲存設備、而非公有雲/超純量基礎架構成本。


NOTE: 超純量型運算與儲存基礎架構並非由NetApp提供、因此您必須向超純量雲端服務供應商購買。
