---
sidebar: sidebar 
permalink: installation/addl-req.html 
keywords: keystone unified manager prerequisites, aiqum config keystone 
summary: Keystone統一化管理程式先決條件 
---
= 其他必要條件、可用於ONTAP 執行效能提升和StorageGRID 效能提升
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您應該完成ONTAP 一些其他的先決條件、以利執行功能和StorageGRID 功能。除了Linux/VMware vSphere系統需求、請確定您已完成這些特定先決條件。按一下所需的索引標籤以深入瞭解。

[role="tabbed-block"]
====
.ONTAP
--
若要在ONTAP 更新版本中安裝Keystone Collector、請先執行下列步驟：

. 確保Active IQ Unified Manager 將某部支援統一化管理程式9.7或更新版本的伺服器設定為支援（Unified Manager）。如需安裝Unified Manager的相關資訊、請參閱下列連結：
+
** https://["在VMware vSphere系統上安裝Unified Manager"^]
** https://["在Linux系統上安裝Unified Manager"^]


. 確保ONTAP 已將該叢集新增至Unified Manager。如需新增叢集的相關資訊、請參閱 https://["新增叢集"^]。
. 建立具有特定角色的Unified Manager使用者、以便收集使用量和效能資料。執行這些步驟。如需使用者角色的相關資訊、請參閱 https://["使用者角色定義"^]。
+
.. 使用安裝期間產生的預設應用程式管理員使用者認證、登入Unified Manager Web UI。請參閱 https://["存取Unified Manager Web UI"^]。
.. 建立Keystone Collector的服務帳戶 `Operator` 使用者角色：Keystone Collector服務API使用此服務帳戶與Unified Manager通訊、並收集使用資料。請參閱 https://["新增使用者"^]。
.. 建立 `Database` 使用者帳戶 `Report Schema` 角色：此使用者是收集效能資料的必要使用者。請參閱 https://["建立資料庫使用者"^]。


. 在Unified Manager中啟用API閘道。Keystone Collector利用API閘道功能與ONTAP 各種叢集進行通訊。您可以從Web UI或透過Unified Manager CLI執行幾個命令來啟用API閘道。
+
.Web UI
若要從Unified Manager Web UI啟用API閘道、請登入Unified Manager Web UI並啟用API閘道。如需相關資訊、請參閱 https://["啟用API閘道"^]。

+
.CLI
若要透過Unified Manager CLI啟用API閘道、請遵循下列步驟：

+
.. 在Unified Manager伺服器上、開始SSH工作階段並登入Unified Manager CLI。
`um cli login -u _<umadmin>_`如需CLI命令的相關資訊、請參閱 https://["支援的Unified Manager CLI命令"^]。
.. 確認API閘道是否已啟用。
`um option list api.gateway.enabled`答 `true` 值表示已啟用API閘道。
.. 如果傳回的值為 `false`請執行下列命令：
`um option set api.gateway.enabled=true`
.. 重新啟動Unified Manager伺服器：
+
*** Linux： https://["重新啟動Unified Manager"^]。
*** VMware vSphere： https://["重新啟動Unified Manager虛擬機器"^]。






--
.StorageGRID
--
若要在StorageGRID 更新版本上安裝Keystone Collector、需要下列組態。

* StorageGRID `11.4.0` 應安裝或更新版本。如需升級StorageGRID 功能的相關資訊、請參閱 link:https://docs.netapp.com/us-en/storagegrid-116/upgrade/index.html["升級StorageGRID 版軟體：總覽"^]。
* 應建立一個支援使用資料收集功能的本地管理員使用者帳戶StorageGRID 。Keystone Collector服務會使用此服務帳戶、StorageGRID 透過管理員節點API與效益進行通訊。
+
.步驟
.. 登入Grid Manager。請參閱 https://["登入Grid Manager"^]。
.. 使用建立本機管理群組 `Access mode: Read-only`。請參閱 https://["建立管理群組"^]。
.. 新增下列權限：
+
*** 租戶帳戶
*** 維護
*** 度量查詢


.. 建立Keystone服務帳戶使用者、並將其與管理群組建立關聯。請參閱 https://["管理使用者"]。




--
====