---
sidebar: sidebar 
permalink: installation/asup-config.html 
keywords: ASUP, AutoSupport configuration 
summary: 設定 Keystone AutoSupport 的程序 
---
= 設定 Keystone 的 AutoSupport
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用 AutoSupport 遙測機制時、 Keystone 服務會根據 AutoSupport 遙測資料執行使用量測。若要達到必要的精細度、您應該將 AutoSupport 設定為將 Keystone 資料納入 ONTAP 叢集所傳送的每日支援套件組合中。

.開始之前
在將 AutoSupport 設定為包含 Keystone 資料之前、請注意下列事項。

* 您可以使用 ONTAP CLI 編輯 AutoSupport 遙測選項。如需管理 AutoSupport 服務和系統（叢集）管理員角色的相關資訊、請參閱 https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["管理AutoSupport 功能概述"^] 和 https://docs.netapp.com/us-en/ontap/system-admin/cluster-svm-administrators-concept.html["叢集與SVM管理員"^]。
* 您可以在 Daily AutoSupport 套裝組合中加入下列子系統、以確保 Keystone 的精確資料收集。如需 AutoSupport 子系統的相關資訊、請參閱 https://docs.netapp.com/us-en/ontap/system-admin/autosupport-subsystem-collection-reference.html["什麼是子系統AutoSupport"^]。
+
|===
| 子系統名稱 | Keystone 所需的資料項目 


 a| 
WAFL
| `VOLUME-CLONE-SHOW.XML` 


 a| 
效能
| `QOS-POLICY-GROUP.XML` 和 `QOS-ADAPTIVE-POLICY.XML` 


 a| 
Snapshot
| `SNAPSHOT.XML` 


 a| 
平台
| `ENVIRONMENT.txt` 
|===
+
依預設、這些子系統會包含在每週的 AutoSupport 套裝組合中、其中包含 `asup_type` 是 _DOT-Regal_ 、以及 `asup_subject` 是 _HA 群組通知（每週記錄）通知 _ 。不過、您需要將它們新增至每日套件組合、以便擷取和報告 Keystone 使用資料。



.步驟
. 以系統管理員使用者身分、使用 SSH 登入 Keystone ONTAP 叢集。如需相關資訊、請參閱 https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-ssh-task.html["使用 SSH 存取叢集"^]。
. 執行下列命令、並驗證現有子系統的現有組態：
+
`autosupport trigger show -node * -autosupport-message management.log -fields basic-additional`

+
如需此命令的詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-manifest-show.html#parameters["系統節點AutoSupport 的資訊清單顯示"^]。

. 執行下列命令來修改每日記錄內容：
+
`autosupport trigger modify -node * -autosupport-message management.log -basic-additional _<existing comma-separated subsystems>_, _<new subsystems>_`

+
如需此命令的詳細資訊、請參閱 https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-trigger-modify.html["系統節點AutoSupport 的不正常情況下修改觸發程序"^]。


