---
sidebar: sidebar 
permalink: installation/install-itom-windows.html 
keywords: Windows installation Keystone, ITOM Collector installation 
summary: 在 Windows 系統上安裝 ITOM Collector 。 
---
= 在 Windows 系統上安裝 ITOM Collector
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
下載 ITOM Collector 安裝檔案，執行 Installshield 精靈，然後輸入必要的監控認證，即可在 Windows 系統上安裝 ITOM Collector 。


NOTE: Keystone 支援團隊提供動態連結，可下載 ITOM Collector 安裝檔案，該檔案將在兩小時內過期。

您可以根據自己的需求，在 Linux 系統上安裝。若要在 Linux 系統上安裝 ITOM Collector ，請link:../installation/install-itom-linux.html["在 Linux 系統上安裝 ITOM Collector"]參閱。

請依照下列步驟，在 Windows 伺服器上安裝 ITOM 收集器軟體：

.開始之前
確保已在 Windows 伺服器本機安全性原則設定的本機原則 / 使用者權限指派下，授予 ITOM 收集器服務 * 以服務身分登入 * 。

.步驟
. 將 ITOM 收集器設定檔下載至 Windows 伺服器。
. 開啟安裝檔案以啟動「 Installshield 精靈」。
. 接受終端使用者授權合約（ EULA ）。InstallShield 精靈會擷取必要的二進位檔，並提示您輸入認證。
. 輸入 ITOM Collector 將在下列情況下執行的帳戶認證：
+
** 如果 ITOM Collector 未監控其他 Windows 伺服器，請使用本機系統。
** 如果 ITOM Collector 正在監控同一個網域中的其他 Windows 伺服器，請使用具有本機系統管理員權限的網域帳戶。
** 如果 ITOM Collector 正在監控其他不屬於同一個網域的 Windows 伺服器，請使用本機系統管理員帳戶，並使用本機系統管理員認證連線至每個資源。您可以選擇設定密碼，使其不會過期，以減少 ITOM 收集器與其受監控資源之間的驗證問題。


. 選取收集器大小。根據設定檔，預設值為建議的大小。除非您有特定需求，否則請繼續使用建議的尺寸。
. 選取 _ 下一步 _ 開始安裝。您可以使用填入的資料夾，或選擇不同的資料夾。狀態方塊會顯示安裝進度，接著顯示「完成安裝精靈」對話方塊。


.接下來呢？
成功安裝時，請聯絡 Keystone 支援團隊，透過 ITOM 支援入口網站驗證是否成功安裝 ITOM Collector 。驗證之後， Keystone 支援團隊將從遠端設定 ITOM Collector ，包括進一步的裝置探索和監控設定，並在組態完成後傳送確認訊息。如有任何疑問或其他資訊，請聯絡 keystone.services@NetApp 。
