---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: 從 YUM 軟體儲存庫安裝 Keystone Collector 軟體。 
---
= 在 Linux 系統上安裝 Keystone Collector
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用 RPM 或 Debian 套件，在 Linux 伺服器上安裝 Keystone Collector 軟體。根據您的 Linux 套裝作業系統，請遵循安裝步驟。

[role="tabbed-block"]
====
.使用 RPM
--
. SSH至Keystone Collector伺服器並升級至 `root` 權限：
. 導入Keystone公共簽章：
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. 請透過檢查 RPM 資料庫中Keystone Billing Platform 的指紋，確保已匯入正確的公共憑證：
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` 正確的指紋如下圖所示：
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. 下載 `keystonerepo.rpm` 文件：
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. 驗證文件的真實性：
`rpm --checksig -v keystonerepo.rpm` 正版文件的簽名如下所示：
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. 安裝YUM軟體儲存庫檔案：
`# yum install keystonerepo.rpm`
. 安裝Keystone repo時、請透過YUM套件管理程式安裝Keystone收集器套件：
+
`# yum install keystone-collector`

+
對於 Red Hat Enterprise Linux 9，執行下列命令安裝 keystone-collector 套件： 
`# yum install keystone-collector-rhel9`



--
.使用 Debian
--
. SSH 至 Keystone Collector 伺服器並提高 `root`權限。
`sudo su`
. 下載 `keystone-sw-repo.deb`檔案：
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. 安裝 Keystone 軟體儲存庫檔案：
`# dpkg -i keystone-sw-repo.deb`
. 更新套件清單：
`# apt-get update`
. 安裝 Keystone repo 後，請安裝 Keystone 收集器套件：
`# apt-get install keystone-collector`


--
====

NOTE: 完成安裝時、您可以使用Keystone Collector Management終端使用者介面（TUI）公用程式來執行組態和監控活動。您可以使用各種鍵盤控制項（例如Enter和方向鍵）來選取選項、並瀏覽此TUI。請參閱 link:../installation/configuration.html["設定Keystone Collector"] 和 link:../installation/monitor-health.html["監控系統健全狀況"] 以取得資訊。
