---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: 舊版 NetApp Keystone STaaS 服務中發現的問題已在後續版本中修正。 
---
= 修正問題
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
舊版 NetApp Keystone STaaS 服務中發現的問題已在後續版本中修正。

[cols="3*"]
|===
| 問題說明 | 修正之後 | 已於版本中修正 


 a| 
從 *Keystone Subscriptions * 頁面上的 *Subscriptions * 標籤中選取 10 至 12 個以上的訂閱時，無法產生訂閱報告。
 a| 
固定
 a| 
2025-01-08



 a| 
在 *Volumes & Objects* 標籤中的 *Volume Summary* 子標籤無法載入 StorageGRID 訂閱。
 a| 
固定
 a| 
2024-11-21



 a| 
當導覽至 *Consumpting Trend* 標籤時、 * 從日期 * 欄位可選取日期範圍、預設會顯示未來日期。
 a| 
固定
 a| 
2024-09-04



 a| 
Keystone Collector 管理 TUI 在設定 AQO 原則時沒有回應。
 a| 
固定
 a| 
2024 年 8 月 7 日



 a| 
使用圖表會顯示超過指定單日期間的資料、當您從 * 容量趨勢 * 標籤的 * 容量趨勢 * 選項中、將對應於當日的日期同時選取為上個月的開始和結束日期時。
 a| 
使用圖表現在可正確顯示指定單日期間的資料。
 a| 
2024 年 6 月 27 日



 a| 
對於未配置 MetroCluster 組態的訂閱、 * 容量趨勢 * 標籤中的 * CVO 主要 * 和 * CVO 次要 * 服務層級、歷史累積突發資料不可用。
 a| 
固定
 a| 
2024 年 6 月 21 日



 a| 
AutoSupport 訂閱的 * Volume Details* 標籤上列出的物件儲存使用值顯示不正確。
 a| 
物件儲存的使用值現在會正確顯示。
 a| 
2024 年 6 月 21 日



 a| 
無法在使用 MetroCluster 組態設定的 AutoSupport 訂閱的 * 資產 * 索引標籤中檢視叢集層級資訊。
 a| 
固定
 a| 
2024 年 6 月 21 日



 a| 
如果從 *Capacity Trend* 標籤產生的 CSV 報告中的 * 帳戶名稱 * 欄包含一個含逗號的帳戶名稱、就會在 CSV 報告中誤置 Keystone 資料 `(,)`。
 a| 
Keystone 資料已在 CSV 報告中正確對齊。
 a| 
2024 年 5 月 29 日



 a| 
即使使用量低於認可容量、仍可從 * 容量趨勢 * 標籤顯示累積的突發使用量。
 a| 
固定
 a| 
2024 年 5 月 29 日



 a| 
*Capacity Trend* 標籤中 * 目前的 Burst * 索引圖示的工具提示文字不正確。
 a| 
顯示正確的工具提示文字「 _ 目前使用的突發容量量。請注意、這是針對目前的計費期間、而非所選的日期範圍。 _ 」
 a| 
2024 年 3 月 28 日



 a| 
如果 Keystone 資料不存在 24 小時、則 AQO 不相容磁碟區和 MetroCluster 合作夥伴的相關資訊將無法用於 AutoSupport 訂閱。
 a| 
固定
 a| 
2024 年 3 月 28 日



 a| 
如果將兩個服務層級指派給一個僅符合一項服務層級的 Volume 、則在 * Volume Summary* 和 * Volume Details* 標籤上列出的 AQO 不相容磁碟區數量偶爾會不相符。
 a| 
固定
 a| 
2024 年 3 月 28 日



 a| 
AutoSupport 訂閱的 * 資產 * 索引標籤上沒有可用的資訊。
 a| 
固定
 a| 
2024 年 3 月 14 日



 a| 
如果在分層和物件儲存的速率計畫均適用的環境中同時啟用 MetroCluster 和 FabricPool 、則鏡射磁碟區（組成磁碟區和 FabricPool 磁碟區）的服務層級可能會不正確地衍生。
 a| 
將正確的服務層級套用至鏡射磁碟區。
 a| 
2024 年 2 月 29 日



 a| 
對於某些具有單一服務層級或費率計畫的訂閱、在 * Volumes （磁碟區） * 標籤報告的 CSV 輸出中、 AQO 法規遵循欄位會遺失。
 a| 
法規遵循欄會顯示在報告中。
 a| 
2024 年 2 月 29 日



 a| 
在某些 MetroCluster 環境中、在 * 效能 * 標籤的 IOPS 密度圖表中偵測到偶爾的異常。這是因為磁碟區對服務層級的對應不正確所致。
 a| 
圖表會正確顯示。
 a| 
2024 年 2 月 29 日



 a| 
突發使用量記錄的使用量指示器會以琥珀色顯示。
 a| 
指示燈會以紅色顯示。
 a| 
2023 年 12 月 13 日



 a| 
容量趨勢、目前使用量和效能標籤中的日期範圍和資料並未轉換為 UTC 時區。
 a| 
所有索引標籤中的查詢和資料日期範圍會以 UTC 時間（伺服器時區）顯示。UTC 時區也會根據索引標籤上的每個日期欄位顯示。
 a| 
2023 年 12 月 13 日



 a| 
索引標籤與下載的 CSV 報告之間的開始日期和結束日期不相符。
 a| 
固定。
 a| 
2023 年 12 月 13 日

|===