---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: NetApp 在每個 Keystone STaaas 服務版本中都提供全新且增強的功能。 
---
= Keystone STaas 的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 在每個 Keystone STaaas 服務版本中都提供全新且增強的功能。

Active IQ Digital Advisor 的 * 基礎概念訂閱 * 畫面（也稱為數位顧問）提供下列增強功能：



== 2024-11-11



=== 增強的報告產生功能

您現在可以使用 Digital Advisor 中的報告功能來產生合併報告，以檢視 Keystone 資料的詳細資料。若要深入瞭解、請 link:../integrations/aiq-keystone-details.html#generate-consolidated-report["產生整合式報告"^]參閱。



== 2024 年 7 月 10 日



=== 標籤修改

標籤 * 目前使用量 * 會變更為 * 目前使用量 * 、而 * 容量趨勢 * 會變更為 * 使用量趨勢 * 。



=== 訂閱搜尋列

* 基礎概念訂閱 * 畫面中所有索引標籤的 * 訂閱 * 下拉式清單現在包含搜尋列。您可以搜尋 * 訂閱 * 下拉式清單中列出的特定訂閱。



== 2024 年 6 月 27 日



=== 一致的訂閱顯示

「 *Keystone Subscriptions * 」畫面會更新、以顯示所有標籤的所選訂閱編號。

* 重新整理 *Keystone Subscriptions* 畫面中的任何標籤時、畫面會自動瀏覽至 *Subscriptions* 標籤、並將所有標籤重設為 *Subscription* 下拉式清單中列出的第一個訂閱。
* 如果所選訂閱未訂閱效能指標、 * 效能 * 索引標籤會在導覽時顯示 * 訂閱 * 下拉式清單中列出的第一個訂閱。




== 2024 年 5 月 29 日



=== 增強的爆發指標

使用圖索引中的 * 脈衝 * 指標會增強、以顯示脈衝量限制百分比值。此值會根據訂閱的約定突發量上限而有所變更。您也可以將游標移到 * 使用狀態 * 欄中的 * 脈衝使用量 * 指標上、以檢視 * 訂閱 * 索引標籤中的突發量限制值。



=== 新增服務層級

包含服務層級 * CVO Primary * 和 * CVO Secondary * 、可支援 Cloud Volumes ONTAP 、以支援具有零承諾容量的費率方案、或是設定為 Metro 叢集的方案。

* 您可以從 *Keystone Subscriptions * Widget 的舊儀表板和 *Capacity Trend* 索引標籤、檢視這些服務層級的容量使用率圖表、也可以從 *Current Usage* 索引標籤檢視詳細的使用資訊。
* 在 * 訂閱 * 索引標籤中、這些服務層級會顯示為 `CVO (v2)` 在 * 使用類型 * 欄中、允許根據這些服務層級來識別帳單。




=== 用於短期突發的放大功能

「 * 容量趨勢 * 」標籤現在包含放大功能、可檢視使用圖表中短期突發的詳細資料。如需更多資訊、請參閱 link:../integrations/capacity-trend-tab.html["容量趨勢索引標籤"^]。



=== 增強訂閱顯示

訂閱的預設顯示功能已增強、可依追蹤 ID 進行排序。* 訂閱 * 索引標籤中的訂閱、包括 * 訂閱 * 下拉式清單和 CSV 報告、現在會依照追蹤 ID 的字母順序、依照 A 、 A 、 b 、 B 等順序顯示。



=== 強化的累積突發顯示

將游標暫留在「 * 容量趨勢 * 」標籤中的容量使用長條圖上時所出現的工具提示、現在會根據已認可的容量、顯示累積突發量的類型。它會區分預提量與發票預提量、顯示 * 預提使用量 * 與 * 發票預提使用量 * 、用於零承諾容量費率方案的訂閱、以及 * 預提突發 * 與 * 發票預提突發 * 、用於非零承諾容量的訂閱。



== 2024 年 5 月 9 日



=== CSV 報告中的新欄

* 容量趨勢 * 索引標籤的 CSV 報告現在包含 * 訂閱號碼 * 和 * 帳戶名稱 * 欄、以提供更好的詳細資料。



=== 增強使用類型欄

「 * 訂閱 * 」標籤中的「 * 使用類型 * 」欄已增強、可將邏輯和實體使用方式顯示為以逗號分隔的值、以涵蓋檔案和物件的服務層級。



=== 從 Volume Details 標籤存取物件儲存詳細資料

「 * 磁碟區與物件 * 」標籤中的「 * 磁碟區詳細資料 * 」標籤現在提供物件儲存詳細資料、以及包含檔案與物件服務層級的訂閱數量資訊。您可以按一下 * Volume Details* 標籤中的 * 物件儲存詳細資料 * 按鈕來檢視詳細資料。



== 2024 年 3 月 28 日



=== 「 Volume Details 」（ Volume 詳細資料）標籤會顯示 QoS 原則符合性的改善

「 * 磁碟區與物件 * 」標籤中的「 * 磁碟區詳細資料 * 」標籤、現在可更清楚地瞭解服務品質（ QoS ）原則法規遵循。先前稱為 *AQoS* 的欄會重新命名為 * 相容 * 、表示 QoS 原則是否符合法規。此外，還會新增一個新欄 *QoS 原則類型 * ，指定原則是固定的還是自適應的。如果兩者皆不適用、欄會顯示 _ 不可用 _ 。如需詳細資訊、請參閱 link:../integrations/volumes-objects-tab.html["Volume  ；物件索引標籤"^]。



=== Volume Summary （ Volume 摘要）選項卡中會顯示新的列和簡化的訂閱

* 「 * 磁碟區與物件 * 」索引標籤中的「 * 磁碟區摘要 * 」索引標籤現在包含標題為 * 受保護 * 的新欄。此欄提供與您訂閱的服務層級相關聯的受保護磁碟區計數。如果您按一下受保護的磁碟區數量、就會進入 * Volume Details* （磁碟區詳細資料）標籤、您可以在其中檢視受保護磁碟區的篩選清單。
* 「 * Volume Summary* 」標籤會更新為僅顯示基本訂閱、不包括附加服務。如需詳細資訊、請參閱 link:../integrations/volumes-objects-tab.html["Volume  ；物件索引標籤"^]。




=== 「容量趨勢」標籤中會顯示「累積突發量明細」的變更

將游標暫留在「 * 容量趨勢 * 」標籤中的容量使用長條圖上時所出現的工具提示、將會顯示當月累積突發的詳細資料。前幾個月將無法取得詳細資料。



=== 增強存取功能、可檢視 Keystone 訂閱的歷史資料

如果已修改或更新 Keystone 訂閱、您現在可以檢視歷史資料。您可以將訂閱的開始日期設定為先前的日期以檢視：

* 使用量與累積的突發使用量資料、請參考 * 容量趨勢 * 標籤、
* 從 * 效能 * 標籤 ONTAP 、


所有這些項目都會根據所選的訂閱日期顯示資料。



== 2024 年 2 月 29 日



=== 新增資產索引標籤

「 * 基礎概念訂閱 * 」畫面現在包含 * 資產 * 索引標籤。這個新索引標籤會根據您的訂閱內容、提供叢集層級的資訊。如需詳細資訊、請參閱 link:../integrations/assets-tab.html["資產索引標籤"^]。



=== 「 Volume & Objects 」標籤的改良功能

為了讓 ONTAP 系統磁碟區更清晰、 * Volume Summary* 和 * Volume Details* 這兩個新的標籤按鈕已新增至 * Volumes * 標籤。「 * Volume Summary 」（ Volume 摘要）標籤提供與您訂閱服務層級相關的整體磁碟區數、包括其 AQO 法規遵循狀態和容量資訊。「 * Volume 詳細資料 * 」標籤會列出所有磁碟區及其詳細資料。如需詳細資訊、請參閱 link:../integrations/volumes-objects-tab.html["Volume  ；物件索引標籤"^]。



=== 增強數位顧問的搜尋體驗

* 數位顧問 * 畫面上的搜尋參數現在包括 Keystone 訂閱號碼和為 Keystone 訂閱所建立的報價表。您可以輸入訂閱號碼或報價表名稱的前三個字元。如需詳細資訊、請參閱 link:../integrations/keystone-aiq.html["檢視 Active IQ Digital Advisor 上的 Keystone 儀表板"^]。



=== 檢視使用資料的時間戳記

您可以在 *Keystone Subscriptions * Widget 的舊儀表板上檢視使用資料時間戳記（以 UTC 為單位）。



== 2024 年 2 月 13 日



=== 可檢視連結至主要訂閱的訂閱

您的部分主要訂閱可能有連結的次要訂閱。如果是這種情況、主要訂閱號碼將繼續顯示在 * 訂閱號碼 * 欄中、而連結的訂閱號碼則會列在 * 訂閱 * 索引標籤上的新欄 * 連結訂閱 * 中。「 * 連結訂閱 * 」欄只有在您有連結的訂閱時才可供使用、而且您可以看到通知您的資訊訊息。



== 2024 年 1 月 11 日



=== 因累積突發而傳回的發票資料

* 累積突發 * 的標籤現已修改為 * 容量趨勢 * 標籤中的 * 發票累積突發 * 。選取此選項可讓您檢視已計費之累積突發資料的每月圖表。如需更多資訊、請參閱 link:../integrations/capacity-trend-tab.html#view-invoiced-accrued-burst["檢視已開發票的累積爆發"^]。



=== 特定費率計畫的累積使用詳細資料

如果您的訂閱具有 _ 零 _ 已認可容量的費率計畫、您可以在 * 容量趨勢 * 標籤中檢視累積的使用量詳細資料。選擇 * 已開票的累計使用 * 選項時、您可以檢視已計費的累計使用資料的每月圖表。



== 2023 年 12 月 15 日



=== 能夠依觀察名單進行搜尋

Digital Advisor 中的報價表支援已延伸至 Keystone 系統。您現在可以使用報價表來搜尋多位客戶的訂閱詳細資料。如需 Keystone STaas 中使用報價表的詳細資訊、請參閱 link:../integrations/keystone-aiq.html#search-by-keystone-watchlists["依 Keystone 觀察名單搜尋"^]。



=== 轉換為 UTC 時區的日期

數位顧問 * Keystone Subscriptions * 畫面上傳回的資料會以 UTC 時間（伺服器時區）顯示。當您輸入查詢日期時、系統會自動將其視為 UTC 時間。如需詳細資訊、請參閱 link:../integrations/aiq-keystone-details.html["Keystone訂閱儀表板與報告"^]。
