---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Keystone STaaS 新功能與增強功能。 
---
= Keystone STaas 的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 在每個 Keystone STaaas 服務版本中都提供全新且增強的功能。



== 2024 年 2 月 29 日的新功能與增強功能

Active IQ Digital Advisor （也稱為數位顧問）儀表板和 * 基礎概念訂閱 * 畫面已針對此版本進行多項增強：



=== 新增資產索引標籤

「 * 基礎概念訂閱 * 」畫面現在包含 * 資產 * 索引標籤。這個新索引標籤會根據您的訂閱內容、提供叢集層級的資訊。如需詳細資訊、請參閱 link:../integrations/assets-tab.html["資產索引標籤"^]。



=== 「 Volume & Objects 」標籤的改良功能

為了讓 ONTAP 系統磁碟區更清晰、 * Volume Summary* 和 * Volume Details* 這兩個新的標籤按鈕已新增至 * Volumes * 標籤。「 * Volume Summary 」（ Volume 摘要）標籤提供與您訂閱服務層級相關的整體磁碟區數、包括其 AQO 法規遵循狀態和容量資訊。「 * Volume 詳細資料 * 」標籤會列出所有磁碟區及其詳細資料。如需詳細資訊、請參閱 link:../integrations/volumes-objects-tab.html["Volume  ；物件索引標籤"^]。



=== 增強數位顧問的搜尋體驗

* 數位顧問 * 畫面上的搜尋參數現在包括 Keystone 訂閱號碼和為 Keystone 訂閱所建立的報價表。您可以輸入訂閱號碼或報價表名稱的前三個字元。如需詳細資訊、請參閱 link:../integrations/keystone-aiq.html["檢視 Active IQ Digital Advisor 上的 Keystone 儀表板"^]。



=== 檢視使用資料的時間戳記

您可以在 *Keystone Subscriptions * Widget 的舊儀表板上檢視使用資料時間戳記（以 UTC 為單位）。



== 2024 年 2 月 13 日的新功能與增強功能

Active IQ Digital Advisor （亦稱為數位顧問）的 * 基礎概念訂閱 * 畫面已進行下列增強。



=== 可檢視連結至主要訂閱的訂閱

您的部分主要訂閱可能有連結的次要訂閱。如果是這種情況、主要訂閱號碼將繼續顯示在 * 訂閱號碼 * 欄中、而連結的訂閱號碼則會列在 * 訂閱 * 索引標籤上的新欄 * 連結訂閱 * 中。「 * 連結訂閱 * 」欄只有在您有連結的訂閱時才可供使用、而且您可以看到通知您的資訊訊息。



== 2024 年 1 月 11 日的新功能與增強功能

瞭解此版本的新功能。

Active IQ Digital Advisor （也稱為數位顧問）的 * 基礎概念訂閱 * 畫面已進行下列增強功能。



=== 因累積突發而傳回的發票資料

* 累積突發 * 的標籤現已修改為 * 容量趨勢 * 標籤中的 * 發票累積突發 * 。選取此選項可讓您檢視已計費之累積突發資料的每月圖表。如需詳細資訊、請參閱 link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["檢視已開發票的累積爆發"^]。



=== 特定費率計畫的累積使用詳細資料

如果您的訂閱具有 _ 零 _ 已認可容量的費率計畫、您可以在 * 容量趨勢 * 標籤中檢視累積的使用量詳細資料。選擇 * 已開票的累計使用 * 選項時、您可以檢視已計費的累計使用資料的每月圖表。



== 2023 年 12 月 15 日的新功能與增強功能

瞭解此版本的新功能。



=== 能夠依觀察名單進行搜尋

Active IQ Digital Advisor （也稱為數位顧問）中的報價表支援已延伸至包含 Keystone 系統。您現在可以使用報價表來搜尋多位客戶的訂閱詳細資料。如需 Keystone STaas 中使用報價表的詳細資訊、請參閱 link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["使用 Keystone 觀察名單進行搜尋"^]。



=== 轉換為 UTC 時區的日期

Active IQ Digital Advisor * Keystone Subscriptions * 畫面上傳回的資料會以 UTC 時間（伺服器時區）顯示。當您輸入查詢日期時、系統會自動將其視為 UTC 時間。如需詳細資訊、請參閱 link:../integrations/aiq-keystone-details.html["Keystone訂閱儀表板與報告"^]。
